version: '3.3'

services:
  census:
    build: ./census/
    tty: true
    command: nodemon --legacy-watch server.js
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - mongo-db
    external_links:
      - mongo-db
    volumes:
      - ./census/app/:/app
      - /app/node_modules
  mongo-db:
    image: mongo
    restart: always
    volumes:
      - mongo-dev:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./.env.dev
    ports:
      - '27017-27019:27017-27019'

volumes:
  mongo-dev:
